apiVersion: apps/v1
kind: Deployment
metadata:
  name: iperf-server-deployment
  labels:
    app: iperf-server
spec:
  replicas: 3
  selector:
    matchLabels:
      app: iperf-server
  template:
    metadata:
      labels:
        app: iperf-server
    spec:
      restartPolicy: Always
      schedulerName: default-scheduler
      nodeSelector:
        redpanda-node: "true"
      tolerations:
      - effect: NoSchedule
        key: redpanda-node
        operator: Equal
        value: "true"
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: kubernetes.io/hostname
          whenUnsatisfiable: ScheduleAnyway
          labelSelector:
            matchLabels:
              app: iperf-server
      containers:
      - name: iperf-server
        image: gokulpch/iperf3-netperf:v1.0
        args: ['-s']
        ports:
        - containerPort: 5201
          name: server
      - name: iperf2-server
        image: mlabbe/iperf
        args: ['-s', '--histograms']
        ports:
        - containerPort: 5001
          name: iperf2server
      terminationGracePeriodSeconds: 0
